# Generated by Django 5.2.1 on 2025-06-11 00:51

import company.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Company Name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=company.models.company_logo_path, verbose_name='Company Logo')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Contact Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Contact Phone')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Company Address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
