# Generated by Django 5.2.1 on 2025-06-11 00:29

import tickets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_remove_ticket_id_remove_ticketcomment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=tickets.models.Ticket.attachment_path),
        ),
    ]
