# Generated by Django 5.2.1 on 2025-06-11 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcomment',
            name='is_progress_update',
            field=models.BooleanField(default=False, help_text='Whether this comment is a progress update'),
        ),
    ]
