# Generated by Django 5.2.1 on 2025-06-12 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticketcomment_is_progress_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('normal', 'Normal (48 horas)'), ('priority', 'Prioritario (24 horas)'), ('urgent', 'Urgente (8 horas)')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Abierto'), ('in_process', 'En Proceso'), ('closed', 'Cerrado')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='is_progress_update',
            field=models.BooleanField(default=False, help_text='Si este comentario es una actualización de progreso'),
        ),
    ]
