# Generated by Django 5.2.1 on 2025-06-26 05:00

# En tickets/migrations/XXXX_fix_ticket_uuid.py
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('tickets', '0007_alter_ticketcomment_ticket'),  # Ajusta al número de tu última migración
    ]

    operations = [
        # Primero eliminamos la constraint de foreign key
        migrations.RunSQL(
            """
            ALTER TABLE tickets_ticketcomment
            DROP
            CONSTRAINT IF EXISTS tickets_ticketcomment_ticket_id_fkey;
            """,
            reverse_sql=""
        ),

        # Convertimos el campo a UUID
        migrations.RunSQL(
            """
            ALTER TABLE tickets_ticketcomment
            ALTER
            COLUMN ticket_id TYPE uuid 
            USING ticket_id::text::uuid;
            """,
            reverse_sql="""
                        ALTER TABLE tickets_ticketcomment
                        ALTER
                        COLUMN ticket_id TYPE integer 
            USING ticket_id::text::integer;
                        """
        ),

        # Recreamos la foreign key constraint
        migrations.RunSQL(
            """
            ALTER TABLE tickets_ticketcomment
                ADD CONSTRAINT tickets_ticketcomment_ticket_id_fkey
                    FOREIGN KEY (ticket_id) REFERENCES tickets_ticket (ticket_id);
            """,
            reverse_sql=""
        ),
    ]
