# Generated by Django 5.2.8 on 2026-08-09 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_auto_20250626_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='requester_email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
    ]
